[package]
name = "find-program-by-name"
version = "0.1.0"
edition = "2018"

[target.'cfg(unix)'.dependencies]
libc = "0.2.98"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["processenv"] }
